#pragma once

#include "cryptodd_arrays_shared_export.h" // Generated by CMake

extern "C"
{
    // This function will be exported from the DLL on Windows
    CRYPTODD_ARRAYS_SHARED_EXPORT void hello();
}
