name: CMake on Windows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main", "abi", "dev" ]
  pull_request:
  workflow_dispatch:

env:
  # BUILD_TYPE is now defined in the job matrix
  VCPKG_DISABLE_METRICS: true
  POWERSHELL_TELEMETRY_OPTOUT: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_TYPE: [RelWithDebInfo, Debug]
        USE_MIMALLOC: [on, off]
        VCPKG_TARGET_TRIPLET: [x64-windows]
    name: '${{ matrix.BUILD_TYPE }} / mimalloc: ${{ matrix.USE_MIMALLOC }} / triplet: ${{ matrix.VCPKG_TARGET_TRIPLET }}'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # --- VCPKG CACHING AND SETUP (Submodule) ---
      - name: Cache vcpkg packages
        uses: actions/cache@v4
        with:
          path: |
            vcpkg/installed
            vcpkg/buildtrees
            vcpkg/downloads
            vcpkg/packages
            vcpkg_installed
            .py-build-cmake_cache/*/vcpkg_installed
            build/vcpkg_installed
          # The cache key should depend on all variables that change dependencies
          key: ${{ runner.os }}-${{ matrix.BUILD_TYPE }}-mimalloc-${{ matrix.USE_MIMALLOC }}-triplet-${{ matrix.VCPKG_TARGET_TRIPLET }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.BUILD_TYPE }}-mimalloc-${{ matrix.USE_MIMALLOC }}-triplet-${{ matrix.VCPKG_TARGET_TRIPLET }}-

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Add msbuild to PATH
        if: ${{ matrix.VCPKG_TARGET_TRIPLET != 'x64-mingw-static' }}
        uses: microsoft/setup-msbuild@v2

      - name: Set up MinGW
        if: ${{ matrix.VCPKG_TARGET_TRIPLET == 'x64-mingw-static' }}
        shell: pwsh
        run: |
          echo "PATH=C:\msys64\usr\bin;$Env:PATH" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
          g++ --version

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Prepare
        shell: pwsh
        run: |
          uv venv --seed
          uv tool install cmake
          uv tool install ninja
          .venv/Scripts/activate
          python ${{github.workspace}}/build_wheel.py --use-mimalloc ${{ matrix.USE_MIMALLOC }} --prepare-only --no-cleanup --skip-git-checks

      - name: Configure CMake
        # Pass the BUILD_TYPE from the matrix and the USE_MIMALLOC option
        # Note: -DUSE_MIMALLOC is technically redundant here because build_wheel.py updates pyproject.toml and CMakeLists.txt
        # to handle this, but keeping it as an explicit parameter is harmless.
        run: cmake -B ${{github.workspace}}/build -DVCPKG_TARGET_TRIPLET=${{ matrix.VCPKG_TARGET_TRIPLET}} -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DUSE_MIMALLOC=${{ matrix.USE_MIMALLOC }} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DMI_SECURE=ON

      - name: Build
        # Use explicit build command
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Use BUILD_TYPE from the matrix
        run: ctest -C ${{matrix.BUILD_TYPE}} -V
        env:
          MIMALLOC_SHOW_STATS: 1
          MIMALLOC_VERBOSE: 1
          MIMALLOC_SHOW_ERRORS: 1

      - name: Upload Build and Test Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          # Use BUILD_TYPE from the matrix in the artifact name
          name: windows-${{matrix.BUILD_TYPE}}-mimalloc-${{ matrix.USE_MIMALLOC }}-triplet-${{ matrix.VCPKG_TARGET_TRIPLET }}-artifacts
          # Use BUILD_TYPE from the matrix in the path
          path: |
            ${{github.workspace}}/build
            !${{github.workspace}}/build/vcpkg_installed
          retention-days: 7