name: CMake on a single platform

on:
  push:
    branches: [ "main", "abi", "dev" ]
  pull_request:
  workflow_dispatch:

env:
  # BUILD_TYPE is now defined in the job matrix
  VCPKG_DISABLE_METRICS: true
  POWERSHELL_TELEMETRY_OPTOUT: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_TYPE: [RelWithDebInfo, Debug]
        USE_MIMALLOC: [on, off]
    name: '${{ matrix.BUILD_TYPE }} / mimalloc: ${{ matrix.USE_MIMALLOC }}'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # --- VCPKG CACHING AND SETUP (Submodule) ---
      - name: Cache vcpkg packages
        uses: actions/cache@v4
        with:
          path: |
            vcpkg/installed
            vcpkg/buildtrees
            vcpkg/downloads
          # The cache key should depend on all variables that change dependencies
          key: ${{ runner.os }}-${{ matrix.BUILD_TYPE }}-mimalloc-${{ matrix.USE_MIMALLOC }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.BUILD_TYPE }}-mimalloc-${{ matrix.USE_MIMALLOC }}-
            ${{ runner.os }}-${{ matrix.BUILD_TYPE }}-mimalloc-
            ${{ runner.os }}-${{ matrix.BUILD_TYPE }}-

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Prepare
        shell: pwsh
        run: |
          uv venv --seed
          uv tool install cmake
          uv tool install ninja
          .venv/Scripts/activate
          # Corrected: Added all required arguments for build_wheel.py
          python ${{github.workspace}}/build_wheel.py --use-mimalloc ${{ matrix.USE_MIMALLOC }} --prepare-only --no-cleanup --skip-git-checks

      - name: Configure CMake
        # Pass the BUILD_TYPE from the matrix and the USE_MIMALLOC option
        # Note: -DUSE_MIMALLOC is technically redundant here because build_wheel.py updates pyproject.toml and CMakeLists.txt
        # to handle this, but keeping it as an explicit parameter is harmless.
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DUSE_MIMALLOC=${{ matrix.USE_MIMALLOC }} -DHWY_DISABLED_TARGETS="(HWY_AVX2|HWY_AVX512|HWY_AVX3|HWY_AVX3_DL|HWY_AVX3_ZEN4|HWY_AVX3_SPR)"

      - name: Build
        # Use explicit build command
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Use BUILD_TYPE from the matrix
        run: ctest -C ${{matrix.BUILD_TYPE}} -V

      - name: Upload Build and Test Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          # Use BUILD_TYPE from the matrix in the artifact name
          name: windows-${{matrix.BUILD_TYPE}}-mimalloc-${{ matrix.USE_MIMALLOC }}-artifacts
          # Use BUILD_TYPE from the matrix in the path
          path: |
            ${{github.workspace}}/build/${{matrix.BUILD_TYPE}}/
            ${{github.workspace}}/build/Testing/
          retention-days: 7